version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      eleventy:
        patterns:
          - "@11ty/*"
          - "eleventy-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
